spring:
  application:
    name: demoEshop

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    open-in-view: false

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  mail:
    host: smtp.gmail.com
    port: 587
    username: testotest1234343535832@gmail.com
    password: abcdabcdabcd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  ai:
    openai.api-key: ${OPEN_AI_KEY}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
  packages-to-scan: com.example.demoeshop.general.controllers

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type: trace
    root: info
    com.example.demoeshop: debug
